# Generated by Django 5.2.7 on 2025-12-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perros/'),
        ),
    ]
